### ISSUE TITLE
Stale session?

### ISSUE THREAD

**Issue by nigelm** [joeshaw/carwings#10]
Sometimes I get a 408 status return from carwings:-

    $ carwings update 
    Logging into Carwings...
    Requesting update from Carwings...
    ERROR: received status code 408

Repeating the command will give the same result. 
Deleting the `~/.carwings-session` file allows the next invocation to work.

Will explore this more when I next see it.  I am using the NE region.

**Comment by joeshaw** [comment]
Error 408 is typically "Request Timeout" -- I suspect if you changed [this line](https://github.com/joeshaw/carwings/blob/master/carwings.go#L393) from `case http.StatusUnauthorized:` to `case http.StatusUnauthorized, http.StatusRequestTimeout:` that might be enough for the CLI to realize it needs to log in again.

**Comment by nigelm** [comment]
Seems like a reasonable approach.  I have seen this 408 a couple more times.  But if a longer period has elapsed between the previous carwings use and then then it appears to re-authenticate OK.

I have put your suggested fix in place for now - see if it works.
