### ISSUE TITLE
"update" polling seems to miss an actual update arriving

### ISSUE THREAD

**Issue by matthewbloch** [joeshaw/carwings#11]
I've been using carwings to poll my car every hour & log its battery level.

Quite often it times out (in Europe at least), and I'm used to the actual service being unreliable.

But does this debug log show carwings missing an actual update when the service was working as expected? I've not looked at the protocol but it looks like it polls and the TargetDate parameters changes from 12:06 to 12:09, but it carries on "waiting for update to complete" and exits with an error.

When I subsequently request the cached battery state, it shows the update that definiedly arrived within about 5s.

Is this a bug? (time zone? I'm in the Europe/London which is 1h behind Europe/Paris).

(a few IDs redacted with ***)

<pre>
$ ./go/bin/carwings -debug update
Logging into Carwings...
POST https://gdcportalgw.its-mo.com/api_v181217_NE/gdc/InitialApp.php map[initial_app_strings:[geORNtsZe5I4lRGjG9GZiA]]
HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Content-Type: text/html; charset=UTF-8
Date: Thu, 07 Mar 2019 12:09:04 GMT
Server: Apache
Strict-Transport-Security: max-age=15768000

45
{"status":200,"message":"success","baseprm":"uyI5Dj9g8VCOFDnBRUbr3g"}
0

Requesting update from Carwings...
POST https://gdcportalgw.its-mo.com/api_v181217_NE/gdc/BatteryStatusCheckRequest.php map[RegionCode:[NE] VIN:[***VIN***] custom_sessionid:[***SESSIONID***] tz:[Europe/Paris]]
HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
Date: Thu, 07 Mar 2019 12:09:05 GMT
Server: Apache
Strict-Transport-Security: max-age=15768000

7c
{"status":200,"userId":"***USERNAME***","vin":"***VIN***","resultKey":"***RESULTKEY***"}
0

Waiting for update to complete... +POST https://gdcportalgw.its-mo.com/api_v181217_NE/gdc/BatteryStatusRecordsRequest.php map[RegionCode:[NE] VIN:[***VIN***] custom_sessionid:[***SESSIONID***] tz:[Europe/Paris]]
HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
Date: Thu, 07 Mar 2019 12:09:10 GMT
Server: Apache
Strict-Transport-Security: max-age=15768000

212
{"status":200,"BatteryStatusRecords":{"OperationResult":"START","OperationDateAndTime":"2019\/03\/07 13:06","BatteryStatus":{"BatteryChargingStatus":"NORMAL_CHARGING","BatteryCapacity":"12","BatteryRemainingAmount":"6","BatteryRemainingAmountWH":"","BatteryRemainingAmountkWH":""},"PluginState":"CONNECTED","CruisingRangeAcOn":"61376.0","CruisingRangeAcOff":"65760.0","TimeRequiredToFull200":{"HourRequiredToFull":"4","MinutesRequiredToFull":"30"},"NotificationDateAndTime":"2019\/03\/07 12:06","TargetDate":"2019\/03\/07 12:06"}}
0

+POST https://gdcportalgw.its-mo.com/api_v181217_NE/gdc/BatteryStatusRecordsRequest.php map[RegionCode:[NE] VIN:[***VIN***] custom_sessionid:[***SESSIONID***] tz:[Europe/Paris]]
HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
Date: Thu, 07 Mar 2019 12:09:15 GMT
Server: Apache
Strict-Transport-Security: max-age=15768000

212
{"status":200,"BatteryStatusRecords":{"OperationResult":"START","OperationDateAndTime":"2019\/03\/07 13:06","BatteryStatus":{"BatteryChargingStatus":"NORMAL_CHARGING","BatteryCapacity":"12","BatteryRemainingAmount":"6","BatteryRemainingAmountWH":"","BatteryRemainingAmountkWH":""},"PluginState":"CONNECTED","CruisingRangeAcOn":"61376.0","CruisingRangeAcOff":"65760.0","TimeRequiredToFull200":{"HourRequiredToFull":"4","MinutesRequiredToFull":"30"},"NotificationDateAndTime":"2019\/03\/07 12:06","TargetDate":"2019\/03\/07 12:06"}}
0

+POST https://gdcportalgw.its-mo.com/api_v181217_NE/gdc/BatteryStatusRecordsRequest.php map[RegionCode:[NE] VIN:[***VIN***] custom_sessionid:[***SESSIONID***] tz:[Europe/Paris]]
HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
Date: Thu, 07 Mar 2019 12:09:20 GMT
Server: Apache
Strict-Transport-Security: max-age=15768000

212
{"status":200,"BatteryStatusRecords":{"OperationResult":"START","OperationDateAndTime":"2019\/03\/07 13:06","BatteryStatus":{"BatteryChargingStatus":"NORMAL_CHARGING","BatteryCapacity":"12","BatteryRemainingAmount":"6","BatteryRemainingAmountWH":"","BatteryRemainingAmountkWH":""},"PluginState":"CONNECTED","CruisingRangeAcOn":"61376.0","CruisingRangeAcOff":"65760.0","TimeRequiredToFull200":{"HourRequiredToFull":"4","MinutesRequiredToFull":"30"},"NotificationDateAndTime":"2019\/03\/07 12:06","TargetDate":"2019\/03\/07 12:06"}}
0

+POST https://gdcportalgw.its-mo.com/api_v181217_NE/gdc/BatteryStatusRecordsRequest.php map[RegionCode:[NE] VIN:[***VIN***] custom_sessionid:[***SESSIONID***] tz:[Europe/Paris]]
HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
Date: Thu, 07 Mar 2019 12:09:25 GMT
Server: Apache
Strict-Transport-Security: max-age=15768000

212
{"status":200,"BatteryStatusRecords":{"OperationResult":"START","OperationDateAndTime":"2019\/03\/07 13:09","BatteryStatus":{"BatteryChargingStatus":"NORMAL_CHARGING","BatteryCapacity":"12","BatteryRemainingAmount":"6","BatteryRemainingAmountWH":"","BatteryRemainingAmountkWH":""},"PluginState":"CONNECTED","CruisingRangeAcOn":"63168.0","CruisingRangeAcOff":"67680.0","TimeRequiredToFull200":{"HourRequiredToFull":"4","MinutesRequiredToFull":"30"},"NotificationDateAndTime":"2019\/03\/07 12:09","TargetDate":"2019\/03\/07 12:09"}}
0

+POST https://gdcportalgw.its-mo.com/api_v181217_NE/gdc/BatteryStatusRecordsRequest.php map[RegionCode:[NE] VIN:[***VIN***] custom_sessionid:[***SESSIONID***] tz:[Europe/Paris]]
HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
Date: Thu, 07 Mar 2019 12:09:30 GMT
Server: Apache
Strict-Transport-Security: max-age=15768000

212
{"status":200,"BatteryStatusRecords":{"OperationResult":"START","OperationDateAndTime":"2019\/03\/07 13:09","BatteryStatus":{"BatteryChargingStatus":"NORMAL_CHARGING","BatteryCapacity":"12","BatteryRemainingAmount":"6","BatteryRemainingAmountWH":"","BatteryRemainingAmountkWH":""},"PluginState":"CONNECTED","CruisingRangeAcOn":"63168.0","CruisingRangeAcOff":"67680.0","TimeRequiredToFull200":{"HourRequiredToFull":"4","MinutesRequiredToFull":"30"},"NotificationDateAndTime":"2019\/03\/07 12:09","TargetDate":"2019\/03\/07 12:09"}}
0

+POST https://gdcportalgw.its-mo.com/api_v181217_NE/gdc/BatteryStatusRecordsRequest.php map[RegionCode:[NE] VIN:[***VIN***] custom_sessionid:[***SESSIONID***] tz:[Europe/Paris]]
HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
Date: Thu, 07 Mar 2019 12:09:35 GMT
Server: Apache
Strict-Transport-Security: max-age=15768000

212
{"status":200,"BatteryStatusRecords":{"OperationResult":"START","OperationDateAndTime":"2019\/03\/07 13:09","BatteryStatus":{"BatteryChargingStatus":"NORMAL_CHARGING","BatteryCapacity":"12","BatteryRemainingAmount":"6","BatteryRemainingAmountWH":"","BatteryRemainingAmountkWH":""},"PluginState":"CONNECTED","CruisingRangeAcOn":"63168.0","CruisingRangeAcOff":"67680.0","TimeRequiredToFull200":{"HourRequiredToFull":"4","MinutesRequiredToFull":"30"},"NotificationDateAndTime":"2019\/03\/07 12:09","TargetDate":"2019\/03\/07 12:09"}}
0

+POST https://gdcportalgw.its-mo.com/api_v181217_NE/gdc/BatteryStatusRecordsRequest.php map[RegionCode:[NE] VIN:[***VIN***] custom_sessionid:[***SESSIONID***] tz:[Europe/Paris]]
HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
Date: Thu, 07 Mar 2019 12:09:40 GMT
Server: Apache
Strict-Transport-Security: max-age=15768000

212
{"status":200,"BatteryStatusRecords":{"OperationResult":"START","OperationDateAndTime":"2019\/03\/07 13:09","BatteryStatus":{"BatteryChargingStatus":"NORMAL_CHARGING","BatteryCapacity":"12","BatteryRemainingAmount":"6","BatteryRemainingAmountWH":"","BatteryRemainingAmountkWH":""},"PluginState":"CONNECTED","CruisingRangeAcOn":"63168.0","CruisingRangeAcOff":"67680.0","TimeRequiredToFull200":{"HourRequiredToFull":"4","MinutesRequiredToFull":"30"},"NotificationDateAndTime":"2019\/03\/07 12:09","TargetDate":"2019\/03\/07 12:09"}}
0

+POST https://gdcportalgw.its-mo.com/api_v181217_NE/gdc/BatteryStatusRecordsRequest.php map[RegionCode:[NE] VIN:[***VIN***] custom_sessionid:[***SESSIONID***] tz:[Europe/Paris]]
HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
Date: Thu, 07 Mar 2019 12:09:45 GMT
Server: Apache
Strict-Transport-Security: max-age=15768000

212
{"status":200,"BatteryStatusRecords":{"OperationResult":"START","OperationDateAndTime":"2019\/03\/07 13:09","BatteryStatus":{"BatteryChargingStatus":"NORMAL_CHARGING","BatteryCapacity":"12","BatteryRemainingAmount":"6","BatteryRemainingAmountWH":"","BatteryRemainingAmountkWH":""},"PluginState":"CONNECTED","CruisingRangeAcOn":"63168.0","CruisingRangeAcOff":"67680.0","TimeRequiredToFull200":{"HourRequiredToFull":"4","MinutesRequiredToFull":"30"},"NotificationDateAndTime":"2019\/03\/07 12:09","TargetDate":"2019\/03\/07 12:09"}}
0

+POST https://gdcportalgw.its-mo.com/api_v181217_NE/gdc/BatteryStatusRecordsRequest.php map[RegionCode:[NE] VIN:[***VIN***] custom_sessionid:[***SESSIONID***] tz:[Europe/Paris]]
HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
Date: Thu, 07 Mar 2019 12:09:50 GMT
Server: Apache
Strict-Transport-Security: max-age=15768000

212
{"status":200,"BatteryStatusRecords":{"OperationResult":"START","OperationDateAndTime":"2019\/03\/07 13:09","BatteryStatus":{"BatteryChargingStatus":"NORMAL_CHARGING","BatteryCapacity":"12","BatteryRemainingAmount":"6","BatteryRemainingAmountWH":"","BatteryRemainingAmountkWH":""},"PluginState":"CONNECTED","CruisingRangeAcOn":"63168.0","CruisingRangeAcOff":"67680.0","TimeRequiredToFull200":{"HourRequiredToFull":"4","MinutesRequiredToFull":"30"},"NotificationDateAndTime":"2019\/03\/07 12:09","TargetDate":"2019\/03\/07 12:09"}}
0

+POST https://gdcportalgw.its-mo.com/api_v181217_NE/gdc/BatteryStatusRecordsRequest.php map[RegionCode:[NE] VIN:[***VIN***] custom_sessionid:[***SESSIONID***] tz:[Europe/Paris]]
HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
Date: Thu, 07 Mar 2019 12:09:55 GMT
Server: Apache
Strict-Transport-Security: max-age=15768000

212
{"status":200,"BatteryStatusRecords":{"OperationResult":"START","OperationDateAndTime":"2019\/03\/07 13:09","BatteryStatus":{"BatteryChargingStatus":"NORMAL_CHARGING","BatteryCapacity":"12","BatteryRemainingAmount":"6","BatteryRemainingAmountWH":"","BatteryRemainingAmountkWH":""},"PluginState":"CONNECTED","CruisingRangeAcOn":"63168.0","CruisingRangeAcOff":"67680.0","TimeRequiredToFull200":{"HourRequiredToFull":"4","MinutesRequiredToFull":"30"},"NotificationDateAndTime":"2019\/03\/07 12:09","TargetDate":"2019\/03\/07 12:09"}}
0

+POST https://gdcportalgw.its-mo.com/api_v181217_NE/gdc/BatteryStatusRecordsRequest.php map[RegionCode:[NE] VIN:[***VIN***] custom_sessionid:[***SESSIONID***] tz:[Europe/Paris]]
HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
Date: Thu, 07 Mar 2019 12:10:00 GMT
Server: Apache
Strict-Transport-Security: max-age=15768000

212
{"status":200,"BatteryStatusRecords":{"OperationResult":"START","OperationDateAndTime":"2019\/03\/07 13:09","BatteryStatus":{"BatteryChargingStatus":"NORMAL_CHARGING","BatteryCapacity":"12","BatteryRemainingAmount":"6","BatteryRemainingAmountWH":"","BatteryRemainingAmountkWH":""},"PluginState":"CONNECTED","CruisingRangeAcOn":"63168.0","CruisingRangeAcOff":"67680.0","TimeRequiredToFull200":{"HourRequiredToFull":"4","MinutesRequiredToFull":"30"},"NotificationDateAndTime":"2019\/03\/07 12:09","TargetDate":"2019\/03\/07 12:09"}}
0

+POST https://gdcportalgw.its-mo.com/api_v181217_NE/gdc/BatteryStatusRecordsRequest.php map[RegionCode:[NE] VIN:[***VIN***] custom_sessionid:[***SESSIONID***] tz:[Europe/Paris]]
HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
Date: Thu, 07 Mar 2019 12:10:06 GMT
Server: Apache
Strict-Transport-Security: max-age=15768000

212
{"status":200,"BatteryStatusRecords":{"OperationResult":"START","OperationDateAndTime":"2019\/03\/07 13:09","BatteryStatus":{"BatteryChargingStatus":"NORMAL_CHARGING","BatteryCapacity":"12","BatteryRemainingAmount":"6","BatteryRemainingAmountWH":"","BatteryRemainingAmountkWH":""},"PluginState":"CONNECTED","CruisingRangeAcOn":"63168.0","CruisingRangeAcOff":"67680.0","TimeRequiredToFull200":{"HourRequiredToFull":"4","MinutesRequiredToFull":"30"},"NotificationDateAndTime":"2019\/03\/07 12:09","TargetDate":"2019\/03\/07 12:09"}}
0

+POST https://gdcportalgw.its-mo.com/api_v181217_NE/gdc/BatteryStatusRecordsRequest.php map[RegionCode:[NE] VIN:[***VIN***] custom_sessionid:[***SESSIONID***] tz:[Europe/Paris]]
HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
Date: Thu, 07 Mar 2019 12:10:11 GMT
Server: Apache
Strict-Transport-Security: max-age=15768000

212
{"status":200,"BatteryStatusRecords":{"OperationResult":"START","OperationDateAndTime":"2019\/03\/07 13:09","BatteryStatus":{"BatteryChargingStatus":"NORMAL_CHARGING","BatteryCapacity":"12","BatteryRemainingAmount":"6","BatteryRemainingAmountWH":"","BatteryRemainingAmountkWH":""},"PluginState":"CONNECTED","CruisingRangeAcOn":"63168.0","CruisingRangeAcOff":"67680.0","TimeRequiredToFull200":{"HourRequiredToFull":"4","MinutesRequiredToFull":"30"},"NotificationDateAndTime":"2019\/03\/07 12:09","TargetDate":"2019\/03\/07 12:09"}}
0

! :-(
ERROR: timed out waiting for update
$ ./go/bin/carwings -debug battery
Logging into Carwings...
POST https://gdcportalgw.its-mo.com/api_v181217_NE/gdc/InitialApp.php map[initial_app_strings:[geORNtsZe5I4lRGjG9GZiA]]
HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Content-Type: text/html; charset=UTF-8
Date: Thu, 07 Mar 2019 12:10:35 GMT
Server: Apache
Strict-Transport-Security: max-age=15768000

45
{"status":200,"message":"success","baseprm":"uyI5Dj9g8VCOFDnBRUbr3g"}
0

Getting latest retrieved battery status...
POST https://gdcportalgw.its-mo.com/api_v181217_NE/gdc/BatteryStatusRecordsRequest.php map[RegionCode:[NE] VIN:[***VIN***] custom_sessionid:[***SESSIONID***] tz:[Europe/Paris]]
HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
Date: Thu, 07 Mar 2019 12:10:36 GMT
Server: Apache
Strict-Transport-Security: max-age=15768000

212
{"status":200,"BatteryStatusRecords":{"OperationResult":"START","OperationDateAndTime":"2019\/03\/07 13:09","BatteryStatus":{"BatteryChargingStatus":"NORMAL_CHARGING","BatteryCapacity":"12","BatteryRemainingAmount":"6","BatteryRemainingAmountWH":"","BatteryRemainingAmountkWH":""},"PluginState":"CONNECTED","CruisingRangeAcOn":"63168.0","CruisingRangeAcOff":"67680.0","TimeRequiredToFull200":{"HourRequiredToFull":"4","MinutesRequiredToFull":"30"},"NotificationDateAndTime":"2019\/03\/07 12:09","TargetDate":"2019\/03\/07 12:09"}}
0

Battery status as of 2019-03-07 13:09:00 +0100 CET:
  Capacity: 6 / 12 (1%)
  Cruising range: 42 miles (39 miles with AC)
  Plug-in state: connected
  Charging status: charging
  Time to full:
    Level 2 charge: 4h30m0s
</pre>

**Comment by joeshaw** [comment]
I suspect that you're right that it's a time zone bug, though that _should_ be accounted for.

If you're comfortable editing the Go code, it would be helpful to add a debug print right before https://github.com/joeshaw/carwings/blob/master/carwings.go#L651

Something like this would help:

```go
fmt.Printf("start: %v (%d)  bs.Timestamp: %v (%d)\n", start, start.UnixNano(), bs.Timestamp, bs.Timestamp.UnixNano())
```

**Comment by matthewbloch** [comment]
Thanks for the pointer Joe – if it looks like a client bug to you I’ll take a look in the next couple of days and see if I can turn it into a PR.
I’d have a go now but Nissan is returning 408s to everything, so I’ll try again later 😊

**Comment by joeshaw** [comment]
Heh, take a look at #10 for the 408 issue.  I think I have a fix for that but I haven't gotten around to apply it yet.

**Comment by joeshaw** [comment]
Ok, it's not a time zone issue.  It is an issue with your update being so early in a minute (4 seconds in from your output), your car updating very quickly, and the fact that the API only updates with minute resolution.  So your car updates in the same minute as you ran the command, and it looks like it happened in the past.  I have a fix for this, I'll push it.
