### ISSUE TITLE
Units issue in monthly report

### ISSUE THREAD

**Issue by nigelm** [joeshaw/carwings#13]
The daily efficiency figure in the monthly report is incorrect - I think it is reporting in units of "10Wh/mile" rather than "kWh/mile"

Example day output:-
```
  Trips on 2019-07-01 Monday
    06:58 25 miles   0.3 kWh/mile
    12:55 0 miles   0.3 kWh/mile
    17:38 27 miles   0.2 kWh/mile
          =======  =======
           52.9miles  23.6 kWh/mile
```

That last line I think should have "0.236 kWh/mile" (or the truncated form of it).

However there is likely some general reworking of the report lines in there - I may have a go at reworking it when I get a little time.

**Comment by joeshaw** [comment]
I would appreciate help on this.  The daily and monthly driving stats have never worked for me.  (In any app, not just this one.)
