### ISSUE TITLE
Europe API endpoints no longer available

### ISSUE THREAD

**Issue by nigelm** [joeshaw/carwings#15]
Looks like the European API endpoints that were being used have been withdrawn:-

```
Logging into Carwings...
POST https://gdcportalgw.its-mo.com/gworchest_160803EC/gdc/InitialApp.php map[initial_app_strings:[geORNtsZe5I4lRGjG9GZiA]]
HTTP/1.1 404 Not Found
```

**Comment by nigelm** [comment]
If you grab the changes from https://gitlab.com/tobiaswkjeldsen/carwingsflutter/commit/76bd35f0bc888c54c2f001ee3d79b4e12e957754 then login works, but things fail later...

**Comment by joeshaw** [comment]
This is affecting me in the US as well, thanks for the heads up.

**Comment by joeshaw** [comment]
Thanks, I just pushed a fix for this.  This API update also broke vehicle location functionality... I haven't been able to find an alternative for that, and I'm tracking it in #16.
