### ISSUE TITLE
Locate vehicle not working after API updates

### ISSUE THREAD

**Issue by joeshaw** [joeshaw/carwings#16]
Late July API update (reflected in 1d31d1a) broke the vehicle location API.  

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /api_v190426_NE/gdc/MyCarFinderRequest.php was not found on this server.</p>
</body></html>
```

I haven't found an alternative yet.

**Comment by stelian42** [comment]
I don't believe there is an alternative, Nissan reportedly removed this in order to "comply" with the European GPRD regulations...
