### ISSUE TITLE
Monthly statistics show incorrect daily summary with unit being kWh/100km

### ISSUE THREAD

**Issue by hardcordaniel** [joeshaw/carwings#19]
Example:

  Trips on 2019-09-02 Monday
    07:49   37.1 km  11.5 kWh/100km     4.3 kWh
    17:32   36.9 km  13.5 kWh/100km     5.0 kWh
          ============ ============== ============
            74.0 km   0.1 kWh/100km     9.2 kWh

The total consumption per 100km is not correct. I think its this line in the code:

efficiency := (power / metersToUnits(cfg.units, distance)) / 1000

which is wrong in this case. Maybe it works if a different "ms.EfficiencyScale" is in effect. I have no idea how to handle this the correct way. Simply dividing by 10 instead of 1000 would fix it for me and probably break it for others.

Is there a more elegant way than to check the string content of "ms.EfficiencyScale"?

**Comment by joeshaw** [comment]
Unfortunately I also don't know how to handle this -- this feature has never worked for me.  (I get empty results from the server whenever I made this request)

If you could attach the output from the API by running with `-debug` (be careful to scrub sensitive information) that might help me decode the API better.

Also cc @nigelm who most recently worked on this feature.

**Comment by stelian42** [comment]
Interestingly, my "ms.EfficiencyScale" is "kWh/km". So the total is correct, but on the other side I found that the resolution of the display is too big: I locally modified the %5.1f into %7.3f for Efficiency in order to have something more readable.

We need to either parse EfficiencyScale or find the way to have a consistent unit but I have no idea where the kWh/km versus kWh/100km come from...

**Comment by nigelm** [comment]
I'll have a look at this, but unfortunately won't be for a few days due to other commitments.

It will also need to be at a time when I'm not getting errors back from the API due to Nissan having issues - `ERROR: json: invalid use of ,string struct tag, trying to unmarshal "" into int`

**Comment by joeshaw** [comment]
> It will also need to be at a time when I'm not getting errors back from the API due to Nissan having issues - `ERROR: json: invalid use of ,string struct tag, trying to unmarshal "" into int`

Given my previous experience with this API, I'd say this is probably not an operational issue on the API side but rather just sloppy implementation.  In other places we have to work around the lax types in this API (a side effect of it being written in PHP, and a downside to using Go for this sort of thing).

We might need to do the same thing here: defining that field as `json.RawMessage` and poking at it directly to see if it should be converted to an int.

**Comment by nigelm** [comment]
So the `ElectricCostScale`  (which becomes the `EfficiencyScale`) can have at least three different values:-

- `kWh/mile` - this is what I see in the UK
- `kWh/km` - as seen by @stelian42 
- `kWh/100km` - as seen by @hardcordaniel 

I guess we need to change the efficiency calculation dependant on that (which can be done by having a branch for the last option, and the existing calculation for the other two and assume for now any other weird units (post Brexit it seems likely the UK will change to Horsepower-hours/furlong) follow the original calculation.

Do we need an enum for that field (sorry my go terminology is likely a bit off here - its not one of my better languages).

**Comment by stelian42** [comment]
It would also be nice to have a config option for choosing the preferred format: I for one would like to have the results in kWh/100km, just like the car dashboard shows...

**Comment by stelian42** [comment]
I've implemented the config option in #21 , I'm not sure if this also fixes the OP issue, please check.

**Comment by stelian42** [comment]
I've added a commit to #21 which I believe it fixes the OP issue.

**Comment by joeshaw** [comment]
Fixed in #21
