### ISSUE TITLE
New Carwings API

### ISSUE THREAD

**Issue by joeshaw** [joeshaw/carwings#3]
There is a new Carwings API available for North American (and possibly Japanese) vehicles.  It is not yet available in Europe.

More info:

Issue #2 
https://github.com/jdhorne/pycarwings2/issues/35#issuecomment-393255266
https://github.com/gboudreau/nissan-connect-php/issues/18
https://gist.github.com/BenWoodford/141ca350445e994e69a70aabfb6db942

**Comment by NickWallbridge** [comment]
@joeshaw Can you do a compile that uses the URL (https://gdcportalgw.its-mo.com/api_v180117_NE/gdc/) that works for region NE? I don't know "Go" at all and my initial attempt to recompile from source failed. Thanks.

**Comment by NickWallbridge** [comment]
Did a "get" this morning and you appear to have implemented the new URL. All is working again for me using region "NE" from the UK. Thank you.

**Comment by joeshaw** [comment]
@BenWoodford on Twitter thinks that the new API may never come to EU Leafs: https://twitter.com/IrregularExpr/status/1001902994110271490

**Comment by Wobbley** [comment]
Anyone know if this endpoint has changed for Europe as well now? (NE) 

I have a custom app since the Nissan EV app literally dosen't work for Android 9 (Pie). It stopped working a day or two ago and I see the endpoint is retrieving a 404.

**Comment by Tobiaswk** [comment]
@joeshaw Do you know if US users still can use the old API that is used in Europe?

**Comment by joeshaw** [comment]
@tobiaswk yes. it works for me, and that’s all this library implements at the moment.

**Comment by Tobiaswk** [comment]
It looks like a new app for european users has been released on Google Play; https://play.google.com/store/apps/details?id=eu.nissan.nissanconnect.services

I'm not sure if this app is only for Nissan Leaf E+ but I am not able to use it with a Nissan Leaf 2018 second generation vehicle. Maybe we have to go though the initial vehicle registration phase a second time?

I have looked at the app binary using apktool. It is using OAuth with this URL; https://prod.eu.auth.kamereon.org/kauth/
I haven't been able to find any others URL of significance within the apk. My guess is that the real API URL is returned by the OAuth upon successful sign in.

Maybe we should make a new issue regarding this?

**Comment by joeshaw** [comment]
A new issue might be good, as the login stuff makes it seem like a pretty different API at first glance.

I'm going to need someone else to do the heavy lifting on reverse engineering the API, as I am in the US, don't have Android, and don't have a Leaf E+.  I'll look around for some other resources for it, however.

**Comment by Tobiaswk** [comment]
No worries! I just wanted to post it here in this discussion to shed some light on it.

fyi I'm the developer of the app My Leaf and the dartcarwings library ;)

**Comment by joeshaw** [comment]
Oh, of course! I recognize your name now. Thanks again for letting me know about the new app and (maybe) API

**Comment by Tobiaswk** [comment]
I've created a Dart client library for North American API tracked here. It supports most of the features the API offers but not all yet; https://github.com/Tobiaswk/dartnissanconnectna
I suppose someone can use it as a reference and make a python implementation.

Just wanted to put that out for anyone interested! ;)

**Comment by howartp84** [comment]
Following.

I'm trying to make use of / update / enhance pycarwings2 to support UK 2019 Leafs (including mine!).

I'm taking over the www.indigodomo.com Home Automation plugin for Leaf, originally written by @JDHorne but abandoned at the same time abandoned the pycarwings2 project.

**Comment by joeshaw** [comment]
I've implemented part of the new API in my new joeshaw/leaf repository.  I decided to make a clean break from the current repo.

**Comment by andig** [comment]
@joeshaw I have a Nissan implementation in Go at https://github.com/andig/evcc/blob/master/internal/vehicle/nissan.go. If there's anything you need to pick for https://github.com/joeshaw/leaf I'd be happy to switch over to your new module again.

**Comment by joeshaw** [comment]
@andig This is the Europe API, correct?  Any idea if it works in other regions?  (USA, Japan)

**Comment by andig** [comment]
It's Europe. If you have credentials for outside I could give it a quick try (pm me at cpuidle@gmx.de).
