### ISSUE TITLE
server endpoints

### ISSUE THREAD

**Issue by gitrago** [joeshaw/carwings#31]
When running in server mode, what endpoints are exposed? I found `http://server:8040/battery` by chance, are there any others?

**Comment by joeshaw** [comment]
Yeah, sorry, I threw that together pretty quickly and never documented it properly.

The endpoints are

```
GET /battery
GET /climate
POST /charging/on
POST /climate/on
POST /climate/off
```

The POST requests have no body.

**Comment by gitrago** [comment]
Thank you very much. Slightly off-topic but I'll ask you anyway: 
My understanding is that a charging session **can** be initiated remotely via the API but it can **not** be stopped, car is charging until SoC=100. On the other hand, a discharge (v2x) **can not** be started remotely on a connected car. Is this true and do you know where to confirm this?

**Comment by joeshaw** [comment]
> My understanding is that a charging session **can** be initiated remotely via the API but it can **not** be stopped, car is charging until SoC=100.

That's my understanding as well, based on the APIs available.

> On the other hand, a discharge (v2x) **can not** be started remotely on a connected car.

I don't know anything about this.  I have a 2017 and have only implemented the older "Carwings" API, which doesn't have any discharge feature.  Do you have a link or reference to it?

**Comment by gitrago** [comment]
No, unfortunately I don't. We have a Leaf 2018 and in theory it supports
v2x. I am at a loss as for where to find documentation on it. CHAdeMO
website maybe?

**Comment by joeshaw** [comment]
Ah, I wasn't familiar with what v2x is.  Just read up on it, looks neat.

I am very doubtful there is API for this -- I imagine the discharging is something that the v2x-capable hardware would initiate through the CHAdeMO connection.

**Comment by joeshaw** [comment]
I've added some documentation to the README about server mode.  I don't think there's any other action to take on this, so I'm closing it out.
