### ISSUE TITLE
BatteryStatus() fails because BatteryRemainingAmountWH is an empty string

### ISSUE THREAD

**Issue by jrester** [joeshaw/carwings#37]
### Error
When calling `BatteryStatus` the function returns an error with the message `ERROR: json: invalid use of ,string struct tag, trying to unmarshal "" into int`. This happens because the `BatteryRemainingAmountWH` field of the response for my nissan leaf is an empty string which cannot be parsed to an valid integer. 

### Response
I am receiving this response:
```json
{
   "OperationResult":"START",
   "OperationDateAndTime":"2021\/06\/01 16:39",
   "BatteryStatus":{
      "BatteryChargingStatus":"NOT_CHARGING",
      "BatteryCapacity":"10",
      "BatteryRemainingAmount":"9",
      "BatteryRemainingAmountWH":"",
      "BatteryRemainingAmountkWH":""
   },
   "PluginState":"CONNECTED",
   "CruisingRangeAcOn":"78848.0",
   "CruisingRangeAcOff":"85888.0",
   "TimeRequiredToFull":{
      "HourRequiredToFull":"3",
      "MinutesRequiredToFull":"0"
   },
   "TimeRequiredToFull200":{
      "HourRequiredToFull":"1",
      "MinutesRequiredToFull":"30"
   },
   "NotificationDateAndTime":"2021\/06\/01 14:39",
   "TargetDate":"2021\/06\/01 14:39"
}
```

### Possible Fix

A possible fix could be to remove the struct tag which tries to unmarshal the string and instead check afterwards if the string is empty and set the value of `RemainingWH` for `BatteryStatus` accordingly. 
I would be happy to implement a fix, if you approve.

**Comment by joeshaw** [comment]
@jrester thanks for the report, I'll look into this.  Could you tell me what model year Leaf you have, and what region of the world you're in?

**Comment by jrester** [comment]
It is from year 2012 type ZE0 and i am from Europe.
