### ISSUE TITLE
Battery SOC is always 1%

### ISSUE THREAD

**Issue by coolchip** [joeshaw/carwings#45]
Hello. First many, many thanks for your work. This is a really great module!

With my Nissan Leaf 2015 I've a problem when reading the Battery SOC. I always get 1%.

'''carwings -username xxxx -password xxxx -region NE -debug battery''' 

results in:

`{"status":200,"BatteryStatusRecords":{"OperationResult":"START","OperationDateAndTime":"2022\/02\/25 13:16","BatteryStatus":{"BatteryChargingStatus":"NOT_CHARGING","BatteryCapacity":"12","BatteryRemainingAmount":"9","BatteryRemainingAmountWH":"","BatteryRemainingAmountkWH":""},"PluginState":"NOT_CONNECTED","CruisingRangeAcOn":"95256.0","CruisingRangeAcOff":"101304.0","TimeRequiredToFull":{"HourRequiredToFull":"5","MinutesRequiredToFull":"30"},"TimeRequiredToFull200":{"HourRequiredToFull":"4","MinutesRequiredToFull":"0"},"TimeRequiredToFull200_6kW":{"HourRequiredToFull":"2","MinutesRequiredToFull":"30"},"NotificationDateAndTime":"2022\/02\/25 12:16","TargetDate":"2022\/02\/25 12:16"}}

Battery status as of 2022-02-25 13:16:00 +0100 CET:
  Capacity: 9 / 12 (1%) 0.0kWh
  Cruising range: 62 miles (59 miles with AC)
  Plug-in state: not connected
  Charging status: not charging
  Time to full:
    Level 1 charge: 5h30m0s
    Level 2 charge: 4h0m0s
    Level 2 at 6 kW: 2h30m0s
`
You can see the Battery is charged to 9 of 12 bars what means 75% SOC. As you also can see in the HTTP Response there is no SOC. So this line is called:
https://github.com/joeshaw/carwings/blob/498fc1f76c02ce67abdea9a5b9400a71ac33b566/carwings.go#L711

And the calculation in this line is (with my data):
Math.Round(9/12) -> 1

The correct calculation has to be:
soc = int(math.Round(float64(remaining) * 100 / float64(batrec.BatteryStatus.BatteryCapacity)))

Then I get the right value. But the question is also why the carwings API does not deliver the SOC.

**Comment by joeshaw** [comment]
Haha oops!  Right you are on the math.

> But the question is also why the carwings API does not deliver the SOC.

I don't have a precise answer for this, but my experience leads me to believe that older model years do not report the exact percentage, just the number of bars remaining and bars of capacity.  I'm not sure exactly where the cutoff is, but as a datapoint my 2017 Leaf reported the percentage.

Thanks for the report, I'll fix it shortly.

**Comment by andig** [comment]
Any Leaf I've seen sofar hat "SoC" afaikt- is yours somehow special?

**Comment by joeshaw** [comment]
The calculation was added in https://github.com/joeshaw/carwings/commit/472119c9bec7a301de32a479399072b3e8cdca49, and the commit message says that pre-2016 models don't report SOC.  Not sure if that's 100% accurate though.

**Comment by joeshaw** [comment]
More context: https://github.com/joeshaw/carwings/issues/1#issuecomment-364331721

**Comment by coolchip** [comment]
Thats possible. I own an 2015'er model

**Comment by coolchip** [comment]
Thank you @joeshaw for that quick fix.

**Comment by emhal** [comment]
Dear @joeshaw I've stumbled upon this issue because my Leaf (ZE0 2014) always shows a too high SOC. For example 133% when full. My Leaf only has 9 of 12 bars capacity left and therefore the implemented calculation
soc = int(math.Round(float64(remaining) * 100 / float64(batrec.BatteryStatus.BatteryCapacity)))
results in my case in this: soc = 12x100/9 = 133
So the current implementation of this calculation works only for Leafs where the battery is not degraded.
The remainig bars are always directly showing the soc (max 12 bars) without the need to take the capacity bars into account.
The correct calculation therefore should be:
soc = int(math.Round(float64(remaining) * 100 / 12))
I would be very happy if you could implement this change :)
