### ISSUE TITLE
CURRENTLY BROKEN: Nissan has changed base URL

### ISSUE THREAD

**Issue by docolli** [joeshaw/carwings#50]
Please change base URL to https://gdcportalgw.its-mo.com/api_v230317_NE/gdc/

**Comment by joeshaw** [comment]
I am in the US and can no longer use this API, so I have no way to test this.  I'd like to gather some info here:

1. Do you have a reference for this URL?  (Did it come from another project like pycarwings?  Pulled out of the app?  Or somewhere else?)
2. What region of the world are you in?
3. What model year and trim level do you have?

I don't have any immediate plans to do this, but longer term I may archive the project, especially if things change more than just the URL on an occasional basis.  Just FYI.

**Comment by docolli** [comment]
Thanks for the quick reply!

1. I extracted this URL from the actual NissanConnected App. I tested this URL with another Carwings implementation in FHEM and after changing the URL the script is running fine again.
2. I am located in Europe/Germany
3. I have a Nissan Leaf ZE1 from 2019.

Your library is used by the cool evcc project and currently the Carwings implementation is broken there.
I guess evcc maintainer @andig already contributed to your project.

From my point of view, just line 53 needs to get edited and it would be cool, if you could do this quickly.

You can test by simple accessing the old URL API call against the new API call.
Old: https://gdcportalgw.its-mo.com/api_v200413_NE/gdc/InitialApp_v2.php
New: https://gdcportalgw.its-mo.com/api_v230317_NE/gdc/InitialApp_v2.php

**Comment by joeshaw** [comment]
I am happy to make the fix!  But I am also happy for you to fork it if you want to take that on.

**Comment by joeshaw** [comment]
I've pushed the fix.  I appreciate your instructions for testing by hitting the old vs. the new URL.

**Comment by docolli** [comment]
Thank you very much for this quick fix!

I was testing in my browser with the same principle to see, if the new URL does work. 😄
