### ISSUE TITLE
Json error on status

### ISSUE THREAD

**Issue by gfaidley** [joeshaw/carwings#8]
I'm not sure if this is related to issue #3 or not but I'm getting an error when running status.  This is on an 2013 SL in North America.

[output.txt](https://github.com/joeshaw/carwings/files/2751703/output.txt)

**Comment by gfaidley** [comment]
Thanks for looking into this.

Yes, this is on update.  I wonder if this is because the older models LEAFs do not report a battery percentage (just the bars).  We talked about that a bit on issue  https://github.com/joeshaw/carwings/issues/1#issuecomment-363267920 I'm not sure that was ever resolved.  It used to report just a 0 but now maybe it's what's causing the issue?

 I'm having a differ issue now too and was not able to run 'battery' response right now.  In fact status does not work either I get a 408 error:
[newError.txt](https://github.com/joeshaw/carwings/files/2752709/newError.txt)

**Comment by joeshaw** [comment]
I fixed the battery percentage issue from #1, so this isn't that.

Nissan has changed things lately which have broken a lot of carwings libraries.  [Some other people](https://github.com/BenWoodford/pycarwings2/commit/1170caf2482b9fbf275e867f55472479197a4660#commitcomment-31894791) have gotten the `{"status":408}` message, but I am not sure what is causing it or how to fix it.

**Comment by joeshaw** [comment]
@gfaidley if you're comfortable editing the Go code, can you try changing the [base URL](https://github.com/joeshaw/carwings/blob/master/carwings.go#L21) to `https://gdcportalgw.its-mo.com/gworchest_160803EC/gdc/` and see if that fixes the 408 error?

Other people report that that URL works for them, but I thought it was only in Europe.

**Comment by gfaidley** [comment]
@joeshaw that seems to have fixed things!  Often times the update command times out before the update is received but eventually it comes through.  Please let me know if there is any other testing I can do to help with this.

**Comment by joeshaw** [comment]
@gfaidley Just coming back to this, can you confirm which (or both, or neither) API works for you?  I know you're in North America, can you let me know which year Leaf you have?

**Comment by gfaidley** [comment]
@joeshaw sorry been away from this a long time.  I have a 2013 (with the modem upgrade).  Let me try to do some testing.  I did have to reach out to Nissan as even the official app was not working.  They were able to fix that (or it coincidently started working around the same time).

**Comment by joeshaw** [comment]
I'm going to close this out, since it was about the JSON error which should now be fixed.  Please open a new issue if you are still seeing issues.
